# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edb62b03d581837f482b563f32d340007b84d7f9f054fa8862be46625f1399fbc8b1e80ed72a82f0e7fc1d72e26aa6f6fd9e081cb1ddf6b47220cdedf86b15e3

test:
  secret_key_base: 51d37e586cf7f3a427d7bcc099cecb13b5f03b3be6b959f27e922b691c9d2f5727a0a394aa7bdccf5fbb1b2a4f7eb6e28d34004728711db3c512a5f84e0f7b94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
